server:
  port: ${PORT:8080}
  tomcat:
    max-swallow-size: -1
spring:
  application:
    name: filekeep
  web:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format-sql: true
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
jwt-secret: ${JWT_SECRET}
jwt-expiration-ms: ${JWT_EXPIRATION}
app:
  base-url: ${BASE_URL}
  sync:
    api-url: ${SYNC_API_URL}
