server:
  port: ${PORT:8080}
  tomcat:
    max-swallow-size: -1
spring:
  application:
    name: filekeep
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
jwt-secret: ${JWT_SECRET}
jwt-expiration-ms: ${JWT_EXPIRATION}
